name: develop -> gh-pages

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.13.2'

      - name: Install dependencies
        run: npm install

      - name: Build static files
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/angular-widget # The folder the action should deploy.

      - name: Version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Branch name
        run: echo running on branch ${GITHUB_REF##*/}

      - name: Commit version
        run: |
          echo git config --global user.name
          echo git config --global user.email
          git add .
          git commit -m "version ${{ env.PACKAGE_VERSION }} [skip ci]"
          git push origin develop
