
name: develop -> gh-pages

on:
  push:
    branches:
      - develop

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install and Build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.0.0
        with:
          token: ${{ secrets.REPO_TOKEN }}
          branch: gh-pages # The branch the action should deploy to.
          folder: dist/angular-widget # The folder the action should deploy.

      - name: Version
        run: node -p -e '`PACKAGE_VERSION=${require("./package.json").version}`' >> $GITHUB_ENV

      - name: Commit version
        run: |
          git add .
          git commit -m "version ${{ env.PACKAGE_VERSION }}"
          git push
